"""Export a resolved label set to other tools.

A tested group of patterns is worth something outside piighost, and a registry
nobody can leave is a registry nobody trusts. Each exporter targets the shape
its tool already consumes, so the output drops in without glue.
"""

import json

from backend.hub.resolve import ResolvedLabels

FORMATS = ("json", "presidio", "spacy")


def to_json(labels: ResolvedLabels) -> str:
    """The plain label-to-regex mapping, with provenance alongside."""
    payload = {
        "ref": labels.ref,
        "engine": "python-re",
        "flags": ["ASCII"],
        "patterns": [
            {
                "label": entry.label,
                "regex": entry.regex,
                "pattern": entry.pattern,
                "via": list(entry.via),
            }
            for entry in labels.labels.values()
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def to_presidio(labels: ResolvedLabels) -> str:
    """A Python module registering one PatternRecognizer per label.

    Every score is 1.0, matching this registry's flat-confidence rule, and no
    context words are declared: Presidio would raise the score of a match near
    one, which would reorder detections the hub deliberately leaves to order.
    """
    lines = [
        '"""Presidio recognizers generated from ' + labels.ref + ".",
        "",
        "Generated by the piighost hub. Do not edit: regenerate instead.",
        "Every pattern matches on shape alone, with no checksum validation, so an",
        "OCR-mangled value is kept rather than dropped.",
        '"""',
        "",
        "from presidio_analyzer import Pattern, PatternRecognizer",
        "",
        "RECOGNIZERS = [",
    ]
    for entry in labels.labels.values():
        lines += [
            "    PatternRecognizer(",
            f"        supported_entity={entry.label!r},",
            "        patterns=[",
            f"            Pattern(name={entry.pattern!r}, regex={entry.regex!r}, score=1.0)",
            "        ],",
            "    ),",
        ]
    lines += [
        "]",
        "",
        "",
        "def register(registry) -> None:",
        '    """Add every recognizer to a Presidio RecognizerRegistry."""',
        "    for recognizer in RECOGNIZERS:",
        "        registry.add_recognizer(recognizer)",
        "",
    ]
    return "\n".join(lines)


def to_spacy(labels: ResolvedLabels) -> str:
    """JSONL patterns for a spaCy EntityRuler, one object per line.

    spaCy matches token by token, so each regex goes in a single-token pattern
    with a REGEX attribute. A value spanning several tokens, an email split on
    its dot or a phone number written in groups, will therefore not match: the
    export is useful for compact values and is documented as partial.
    """
    lines = [
        json.dumps(
            {"label": entry.label, "pattern": [{"TEXT": {"REGEX": entry.regex}}]},
            ensure_ascii=False,
        )
        for entry in labels.labels.values()
    ]
    return "\n".join(lines) + "\n"


def export(labels: ResolvedLabels, fmt: str) -> tuple[str, str]:
    """Return the exported body and its media type."""
    if fmt == "json":
        return to_json(labels), "application/json"
    if fmt == "presidio":
        return to_presidio(labels), "text/x-python"
    if fmt == "spacy":
        return to_spacy(labels), "application/x-ndjson"
    raise ValueError(f"unknown export format {fmt!r}")


def snippets(ref: str, kind: str) -> dict[str, str]:
    """Ready-to-paste ways to use a reference, one per target."""
    pinned = ref
    common = {
        "cli": f"piighost hub pull {pinned} -o pipeline.toml\n"
        f'piighost anonymize "mail me at a@b.co" --config pipeline.toml',
        "curl": f"curl -o pipeline.toml \\\n  '{_url(pinned)}/pipeline.toml'",
        "docker": f"docker run --rm -e PIIGHOST_CONFIG={pinned} \\\n"
        f"  ghcr.io/athroniaeth/piighost-api:latest",
    }
    if kind == "config":
        common["python"] = (
            "from piighost.config import load_pipeline\n\n"
            f'pipeline = load_pipeline("hub:{pinned}")\n'
            'result = await pipeline.anonymize("mail me at a@b.co")'
        )
    else:
        common["python"] = (
            "from piighost.components.detector import RegexDetector\n"
            "from piighost.pipeline import AnonymizationPipeline\n\n"
            "# The flattened export inlines every regex, so nothing resolves at runtime.\n"
            "detector = RegexDetector(PATTERNS)  # from the JSON export\n"
            "pipeline = AnonymizationPipeline(detector)"
        )
    return common


def _url(ref: str) -> str:
    key, _, selector = ref.partition(":")
    return f"/api/v1/refs/{key}/{selector}"
