"""Export a resolved label set to other tools.

A tested group of patterns is worth something outside piighost, and a registry
nobody can leave is a registry nobody trusts. Each exporter targets the shape
its tool already consumes, so the output drops in without glue.
"""

import json

from backend.hub.resolve import ResolvedLabels

FORMATS = ("json", "presidio", "spacy")


def to_json(labels: ResolvedLabels) -> str:
    """The plain label-to-regex mapping, with provenance alongside."""
    payload = {
        "ref": labels.ref,
        "engine": "python-re",
        "flags": ["ASCII"],
        "patterns": [
            {
                "label": entry.label,
                "regex": entry.regex,
                "pattern": entry.pattern,
                "via": list(entry.via),
            }
            for entry in labels.labels.values()
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def to_presidio(labels: ResolvedLabels) -> str:
    """A Python module registering one PatternRecognizer per label.

    Every score is 1.0, matching this registry's flat-confidence rule, and no
    context words are declared: Presidio would raise the score of a match near
    one, which would reorder detections the hub deliberately leaves to order.
    """
    lines = [
        '"""Presidio recognizers generated from ' + labels.ref + ".",
        "",
        "Generated by the piighost hub. Do not edit: regenerate instead.",
        "Every pattern matches on shape alone, with no checksum validation, so an",
        "OCR-mangled value is kept rather than dropped.",
        '"""',
        "",
        "from presidio_analyzer import Pattern, PatternRecognizer",
        "",
        "RECOGNIZERS = [",
    ]
    for entry in labels.labels.values():
        lines += [
            "    PatternRecognizer(",
            f"        supported_entity={entry.label!r},",
            "        patterns=[",
            f"            Pattern(name={entry.pattern!r}, regex={entry.regex!r}, score=1.0)",
            "        ],",
            "    ),",
        ]
    lines += [
        "]",
        "",
        "",
        "def register(registry) -> None:",
        '    """Add every recognizer to a Presidio RecognizerRegistry."""',
        "    for recognizer in RECOGNIZERS:",
        "        registry.add_recognizer(recognizer)",
        "",
    ]
    return "\n".join(lines)


def to_spacy(labels: ResolvedLabels) -> str:
    """JSONL patterns for a spaCy EntityRuler, one object per line.

    spaCy matches token by token, so each regex goes in a single-token pattern
    with a REGEX attribute. A value spanning several tokens, an email split on
    its dot or a phone number written in groups, will therefore not match: the
    export is useful for compact values and is documented as partial.
    """
    lines = [
        json.dumps(
            {"label": entry.label, "pattern": [{"TEXT": {"REGEX": entry.regex}}]},
            ensure_ascii=False,
        )
        for entry in labels.labels.values()
    ]
    return "\n".join(lines) + "\n"


def export(labels: ResolvedLabels, fmt: str) -> tuple[str, str]:
    """Return the exported body and its media type."""
    if fmt == "json":
        return to_json(labels), "application/json"
    if fmt == "presidio":
        return to_presidio(labels), "text/x-python"
    if fmt == "spacy":
        return to_spacy(labels), "application/x-ndjson"
    raise ValueError(f"unknown export format {fmt!r}")


MIN_VERSION = "1.8"
"""The piighost release that ships RegexDetector.from_hub and hub catalogs."""


def snippets(ref: str, kind: str, *, origin: str, regex_only: bool) -> dict[str, str]:
    """Ready-to-paste ways to use a reference: from Python, or from a config.

    The registry hands out regexes, so both recipes are about the detector.
    What a pipeline does afterwards — link, anonymize, remember — is the
    application's to choose, and a hub that picked those for you would be a
    different kind of thing.

    ``regex_only`` says the rendered detector is a plain regex one, which is
    every pattern and group and all but three configs. Those three carry a
    model detector: their regexes are half the object, so they are shown being
    built whole and get no catalog recipe, since a catalogs entry cannot say
    model.
    """
    if not regex_only:
        return {"python": _whole_pipeline(ref, origin)}
    return {"python": _from_hub(ref), "config": _catalog(ref)}


def _from_hub(ref: str) -> str:
    """The detector by its id, which is what the registry is for."""
    return (
        f"# needs piighost >= {MIN_VERSION}\n"
        "from piighost.components.detector import RegexDetector\n\n"
        f'detector = RegexDetector.from_hub("{ref}")\n'
        'found = await detector.detect("mail me at a@b.co")'
    )


def _catalog(ref: str) -> str:
    """The same reference named from a pipeline file, fetched when it builds."""
    return (
        "# pipeline.toml\n"
        "[detector]\n"
        "type = 'regex'\n"
        f"catalogs = ['hub:{ref}']\n"
        "\n"
        "# Your own on top: an inline pattern wins on a shared label.\n"
        "[detector.patterns]\n"
        "INTERNAL_ID = 'EMP-\\d{6}'"
    )


def _whole_pipeline(ref: str, origin: str) -> str:
    """A reference carrying a model detector is used whole, or not at all."""
    key, _, selector = ref.partition(":")
    url = f"{origin}/api/v1/refs/{key}/{selector}/pipeline.toml"
    return (
        "# This one carries a model detector as well as regexes, so it is\n"
        "# built whole rather than lifted apart.\n"
        "import tomllib\n"
        "import urllib.request\n\n"
        "from piighost.config import PipelineConfig\n\n"
        f'URL = "{url}"\n'
        "config = tomllib.loads(urllib.request.urlopen(URL).read().decode())\n\n"
        "pipeline = PipelineConfig.model_validate(config).build()\n"
        'result = await pipeline.anonymize("mail me at a@b.co")'
    )
