"""Export a resolved label set to other tools.

A tested group of patterns is worth something outside piighost, and a registry
nobody can leave is a registry nobody trusts. Each exporter targets the shape
its tool already consumes, so the output drops in without glue.
"""

import json

from backend.hub.resolve import ResolvedLabels

FORMATS = ("json", "presidio", "spacy")


def to_json(labels: ResolvedLabels) -> str:
    """The plain label-to-regex mapping, with provenance alongside."""
    payload = {
        "ref": labels.ref,
        "engine": "python-re",
        "flags": ["ASCII"],
        "patterns": [
            {
                "label": entry.label,
                "regex": entry.regex,
                "pattern": entry.pattern,
                "via": list(entry.via),
            }
            for entry in labels.labels.values()
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def to_presidio(labels: ResolvedLabels) -> str:
    """A Python module registering one PatternRecognizer per label.

    Every score is 1.0, matching this registry's flat-confidence rule, and no
    context words are declared: Presidio would raise the score of a match near
    one, which would reorder detections the hub deliberately leaves to order.
    """
    lines = [
        '"""Presidio recognizers generated from ' + labels.ref + ".",
        "",
        "Generated by the piighost hub. Do not edit: regenerate instead.",
        "Every pattern matches on shape alone, with no checksum validation, so an",
        "OCR-mangled value is kept rather than dropped.",
        '"""',
        "",
        "from presidio_analyzer import Pattern, PatternRecognizer",
        "",
        "RECOGNIZERS = [",
    ]
    for entry in labels.labels.values():
        lines += [
            "    PatternRecognizer(",
            f"        supported_entity={entry.label!r},",
            "        patterns=[",
            f"            Pattern(name={entry.pattern!r}, regex={entry.regex!r}, score=1.0)",
            "        ],",
            "    ),",
        ]
    lines += [
        "]",
        "",
        "",
        "def register(registry) -> None:",
        '    """Add every recognizer to a Presidio RecognizerRegistry."""',
        "    for recognizer in RECOGNIZERS:",
        "        registry.add_recognizer(recognizer)",
        "",
    ]
    return "\n".join(lines)


def to_spacy(labels: ResolvedLabels) -> str:
    """JSONL patterns for a spaCy EntityRuler, one object per line.

    spaCy matches token by token, so each regex goes in a single-token pattern
    with a REGEX attribute. A value spanning several tokens, an email split on
    its dot or a phone number written in groups, will therefore not match: the
    export is useful for compact values and is documented as partial.
    """
    lines = [
        json.dumps(
            {"label": entry.label, "pattern": [{"TEXT": {"REGEX": entry.regex}}]},
            ensure_ascii=False,
        )
        for entry in labels.labels.values()
    ]
    return "\n".join(lines) + "\n"


def export(labels: ResolvedLabels, fmt: str) -> tuple[str, str]:
    """Return the exported body and its media type."""
    if fmt == "json":
        return to_json(labels), "application/json"
    if fmt == "presidio":
        return to_presidio(labels), "text/x-python"
    if fmt == "spacy":
        return to_spacy(labels), "application/x-ndjson"
    raise ValueError(f"unknown export format {fmt!r}")


def snippets(ref: str, kind: str, *, origin: str, regex_only: bool) -> dict[str, str]:
    """Ready-to-paste ways to use a reference, one per target.

    Every recipe here was run against piighost 1.7.1 and the published image
    before being written down. That matters because the obvious ones do not
    work: the library has no hub client — ``load_pipeline`` takes a path and
    there is no ``piighost hub`` command — so a snippet that resolves a
    ``hub:`` reference by itself is fiction. Each one fetches the file over
    HTTP instead.

    ``regex_only`` says the rendered detector is a plain regex one, which is
    every pattern and group and all but three configs. Those three carry a
    model detector, where taking the patterns out would silently drop half the
    pipeline, so they get the pipeline form.
    """
    key, _, selector = ref.partition(":")
    base = f"{origin}/api/v1/refs/{key}/{selector}/pipeline.toml"
    url = f"{base}?part=detector" if regex_only else base
    file = "detector.toml" if regex_only else "pipeline.toml"

    items = {
        "cli": (
            "# piighost has no hub client yet, so the file comes over HTTP.\n"
            f"curl -o {file} \\\n  '{url}'\n"
            f'piighost anonymize "mail me at a@b.co" --config {file}'
        ),
        "curl": f"curl -o {file} \\\n  '{url}'",
        "python": _python(url, regex_only, kind),
    }
    if kind == "config":
        # Only a config boots the published image: it runs piighost 1.3.0,
        # where the linker and the anonymizer are required, and a group's
        # rendered file carries neither. It also serves threads, hence the
        # memory, and refuses to start unauthenticated without the opt-in.
        items["docker"] = (
            f"curl -o pipeline.toml \\\n  '{base}?memory=in_memory'\n"
            "docker run --rm -p 8000:8000 \\\n"
            "  -e PIIGHOST_ALLOW_ANONYMOUS=true \\\n"
            '  -v "$PWD/pipeline.toml:/app/pipeline.toml" \\\n'
            "  ghcr.io/athroniaeth/piighost-api:latest"
        )
    return items


def _python(url: str, regex_only: bool, kind: str) -> str:
    """The detector by its id, which is what the registry is for."""
    if not regex_only:
        return (
            "import tomllib\n"
            "import urllib.request\n\n"
            "from piighost.config import PipelineConfig\n\n"
            f'URL = "{url}"\n'
            "config = tomllib.loads(urllib.request.urlopen(URL).read().decode())\n\n"
            "pipeline = PipelineConfig.model_validate(config).build()\n"
            'result = await pipeline.anonymize("mail me at a@b.co")'
        )
    body = (
        "import tomllib\n"
        "import urllib.request\n\n"
        "from piighost.components.detector import RegexDetector\n\n"
        f'URL = "{url}"\n'
        "config = tomllib.loads(urllib.request.urlopen(URL).read().decode())\n\n"
        'detector = RegexDetector(config["detector"]["patterns"])\n'
        'found = await detector.detect("mail me at a@b.co")'
    )
    if kind == "config":
        body += (
            "\n\n# For the whole pipeline instead, drop ?part=detector and:\n"
            "#   pipeline = PipelineConfig.model_validate(config).build()"
        )
    return body
